spring:
  application:
    name: apigw

server:
  port: 8080

zuul:
  routes:
    links:
      path: /links/**
      serviceId: linkservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://serviceregistry:8761/eureka/